# This is a basic workflow to help you get started with Actions

name: Helm

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - run: mkdir zip
      - uses: actions/checkout@master
      #- name: Archive Release
      #  uses: thedoctor0/zip-release@master
      #  with:
      #    directory: 'deploy/helm'
      #    filename: 'chart.zip'
      - uses: actions/upload-artifact@master
        with:
          name: chart
          path: deploy/helm/
